### ISSUE TITLE
Typo in Intro to Electronics > L3: Ohm's Law > Common SI Prefixes Table

### ISSUE THREAD

**Issue by logansw** [makeabilitylab/physcomp#29]
The last row of the Common SI Prefixes Table repeats nano; I believe this should be pico at 10^-12!

**Comment by jonfroehlich** [comment]
Right you are @logansw. Fixing now:
![image](https://user-images.githubusercontent.com/1621749/114223856-29429080-9925-11eb-9175-2cb17bad5364.png)

to:

![image](https://user-images.githubusercontent.com/1621749/114223914-3fe8e780-9925-11eb-8568-65527294e36a.png)

**Comment by jonfroehlich** [comment]
Before:

![image](https://user-images.githubusercontent.com/1621749/114224093-7aeb1b00-9925-11eb-8890-68fb288dbdd1.png)

After:

![image](https://user-images.githubusercontent.com/1621749/114224229-a837c900-9925-11eb-9472-7ec70663fa3b.png)
