### ISSUE TITLE
I think its a typo error that frequency is in MHz instead of being in Hz

### ISSUE THREAD

**Issue by navig2712** [makeabilitylab/physcomp#65]
**The Freq should be in Hz i guess its a typo **
the Arduino Uno supplies a "**490MHz**" PWM waveform at 8 bits. And this is more than fast enough to smoothly fade between different LED brightness levels. So, you can always start there ("**490MHz**" freq, 8-bit resolution) and then play around.

**Comment by jonfroehlich** [comment]
Great catch. Fixed now in https://github.com/makeabilitylab/physcomp/commit/720e32cb88207747b68b03257ef15cbe83b49b11. Thanks!
