### ISSUE TITLE
minor documentation error

### ISSUE THREAD

**Issue by adavid7** [makeabilitylab/physcomp#73]
On this page: [Lesson 1: Intro to the CPX](https://makeabilitylab.github.io/physcomp/cpx/cpx.html), the first ¶ contains a few documentation errors:

1. The name of the platform is "Circuit Playground Express", not "Circuit Express Playground".
2. It is a collaboration between Adafruit and [Microsoft](https://www.microsoft.com/en-us/makecode) (who developed the original base platform MakeCode), not code.org.

**Comment by jonfroehlich** [comment]
Great catch @adavid7! Fixed in https://github.com/makeabilitylab/physcomp/commit/0acc93e70fd6da09727c686ddbb98031d5288192
